- name: configure ci
  hosts: role_ci
  become: true
  roles:
  - roles/common
  - roles/ci

- name: configure deploy
  hosts: role_appserver
  become: true
  roles:
  - roles/common
  - roles/deploy
