#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/ci
- name: install prereqs
  ansible.builtin.apt:
    name:
    - software-properties-common
    - openjdk-21-jre
    - fontconfig
    state: present
    update_cache: true
- name: add gpg key
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    state: present
- name: add apt repo
  ansible.builtin.apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
- name: install pkg
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: true
  notify: restart jenkins
- name: setup sudo
  ansible.builtin.copy:
    src: jenkins.conf
    dest: /etc/sudoers.d/jenkins.conf
  notify: restart jenkins
